# Generated by Django 4.2.2 on 2023-07-04 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookcomment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                related_name="book",
                to="book.category",
                verbose_name="Kitob kategoriyasi",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="collection_book",
            field=models.ManyToManyField(
                blank=True,
                related_name="book",
                to="book.collectionbook",
                verbose_name="Kitob toplami",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="book",
                to="book.tag",
                verbose_name="Kalit so`zlar",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="wishlist",
            field=models.ManyToManyField(
                blank=True, related_name="book", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
