# Generated by Django 4.2.2 on 2023-06-12 03:47

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '2. Kitob kategoriyasi', 'verbose_name_plural': '2. Kitoblar kategoriyasi'},
        ),
        migrations.AlterModelOptions(
            name='collectionbook',
            options={'verbose_name': '4. Kitob toplami', 'verbose_name_plural': '4. Kitoblar toplami'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '3. Kitob kalit so`zlari', 'verbose_name_plural': '3. Kitoblar kalit so`zlari'},
        ),
        migrations.RemoveField(
            model_name='collectionbook',
            name='url',
        ),
        migrations.AddField(
            model_name='collectionbook',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Toplam haqida'),
        ),
        migrations.AddField(
            model_name='collectionbook',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Toplam haqida qisqacha'),
        ),
        migrations.AddField(
            model_name='collectionbook',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Narxi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectionbook',
            name='slug',
            field=models.SlugField(default=1, max_length=350, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectionbook',
            name='special_status',
            field=models.CharField(choices=[('True', 'Maqsus toplam'), ('False', 'Oddiy toplam')], default='False', max_length=20, verbose_name='Sotuv holati'),
        ),
        migrations.AddField(
            model_name='collectionbook',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Toplam nomi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=350, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='collectionbook',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/', verbose_name='Toplam rasmi'),
        ),
        migrations.AlterField(
            model_name='collectionbook',
            name='status',
            field=models.CharField(choices=[('True', 'Mavjud'), ('False', 'Mavjud emas')], default='True', max_length=15, verbose_name='Mavjudligi'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=350, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Kalit so`z nomi'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Kalit so`z nomi'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Kalit so`z nomi'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Kalit so`z nomi'),
        ),
        migrations.CreateModel(
            name='CollectionSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='collection/')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectionslider', to='book.collectionbook')),
            ],
            options={
                'verbose_name': '6. Collection slider rasmi',
                'verbose_name_plural': '6. Collection slider rasmi',
            },
        ),
    ]
