# Generated by Django 4.1.2 on 2022-11-20 12:48

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/')),
                ('url', models.CharField(blank=True, max_length=555)),
                ('status', models.CharField(choices=[('True', 'Available'), ('False', 'Not Available')], default='True', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
