# Generated by Django 4.2.2 on 2023-06-12 08:27

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_alter_category_options_alter_collectionbook_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '1. Kitob', 'verbose_name_plural': '1. Kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='bookcomment',
            options={'verbose_name': '5. Kitob izohi', 'verbose_name_plural': '5. Kitoblar izohi'},
        ),
        migrations.AlterModelOptions(
            name='bookslider',
            options={'verbose_name': '6. Kitob slider rasmi', 'verbose_name_plural': '6. Kitoblar slider rasmi'},
        ),
        migrations.AddField(
            model_name='book',
            name='collection_book',
            field=models.ManyToManyField(blank=True, related_name='book', to='book.collectionbook', verbose_name='Kitob toplami'),
        ),
        migrations.AddField(
            model_name='book',
            name='count_comment',
            field=models.IntegerField(default=0, verbose_name='Izohlar soni'),
        ),
        migrations.AddField(
            model_name='book',
            name='date_published',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kitob shiqgan sana'),
        ),
        migrations.AddField(
            model_name='book',
            name='discount_price',
            field=models.IntegerField(default=0, verbose_name='Chegirma'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kitob tili'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kim tomonidan nashr qilindi'),
        ),
        migrations.AddField(
            model_name='book',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='book', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Muallifi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='book', to='book.category', verbose_name='Kitob kategoriyasi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='coverpage',
            field=imagekit.models.fields.ProcessedImageField(upload_to='books/', verbose_name='Kitobning rasmi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Kitob haqida'),
        ),
        migrations.AlterField(
            model_name='book',
            name='detail_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Kitob haqida'),
        ),
        migrations.AlterField(
            model_name='book',
            name='detail_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Kitob haqida'),
        ),
        migrations.AlterField(
            model_name='book',
            name='detail_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Kitob haqida'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Reyting'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sales_status',
            field=models.CharField(choices=[('CHEGIRMA', 'CHEGIRMA'), ('YANGI', 'YANGI'), ('FALSE', 'Yoq')], default='False', max_length=15, verbose_name='Sotuvdagi holati'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=350, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('True', 'Mavjud'), ('False', 'Mavjud emas')], default='True', max_length=10, verbose_name='Kitob Mavjudligi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='book', to='book.tag', verbose_name='Kalit so`zlar'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Kitob nomi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_en',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Kitob nomi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Kitob nomi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Kitob nomi'),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookcomment', to='book.book'),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='status',
            field=models.CharField(choices=[('True', 'Mavjud'), ('False', 'Mavjud emas')], default='True', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookcomment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookslider',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookslider', to='book.book'),
        ),
    ]
