# Generated by Django 4.2.2 on 2023-07-04 15:59

import ckeditor_uploader.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "Mavjud"), ("False", "Mavjud emas")],
                        default="False",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("detail", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "detail_uz",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "detail_en",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "detail_ru",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
            ],
            options={
                "verbose_name": "6. Biz haqqimizda malumot",
                "verbose_name_plural": "6. Biz haqqimizda malumot",
            },
        ),
        migrations.CreateModel(
            name="CommonInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "Mavjud"), ("False", "Mavjud emas")],
                        default="False",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="images/")),
                ("description_contact", models.TextField(blank=True, null=True)),
                ("description_contact_uz", models.TextField(blank=True, null=True)),
                ("description_contact_en", models.TextField(blank=True, null=True)),
                ("description_contact_ru", models.TextField(blank=True, null=True)),
                ("description_footer", models.TextField(blank=True, null=True)),
                ("description_footer_uz", models.TextField(blank=True, null=True)),
                ("description_footer_en", models.TextField(blank=True, null=True)),
                ("description_footer_ru", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.CharField(blank=True, max_length=50, null=True)),
                ("telegram", models.CharField(blank=True, max_length=255, null=True)),
                ("instagram", models.CharField(blank=True, max_length=255, null=True)),
                ("facebook", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "1. Saytning umimiy malumoti",
                "verbose_name_plural": "1. Saytning umimiy malumoti",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=222)),
                ("phone", models.CharField(max_length=222)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField(max_length=500)),
                ("ip", models.CharField(blank=True, max_length=155, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "Oqilgan"), ("False", "Oqilmagan")],
                        default="False",
                        max_length=10,
                    ),
                ),
                ("read", models.BooleanField(default=False, editable=False)),
            ],
            options={
                "verbose_name": "4. Bizga kelgan xabar",
                "verbose_name_plural": "4. Bizga kelgan xabarlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscountInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "Mavjud"), ("False", "Mavjud emas")],
                        default="False",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("detail", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "detail_uz",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "detail_en",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "detail_ru",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
            ],
            options={
                "verbose_name": "9. Chegirmalar haqqida",
                "verbose_name_plural": "9. Chegirmalar haqqida",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "Mavjud"), ("False", "Mavjud emas")],
                        default="False",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "5. Ko`p beriladigan savol",
                "verbose_name_plural": "5. Ko`p beriladigan savollar",
            },
        ),
        migrations.CreateModel(
            name="HeadImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "Mavjud"), ("False", "Mavjud emas")],
                        default="False",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(upload_to="images/"),
                ),
            ],
            options={
                "verbose_name": "3. Sahifalarda shiqadigan rasm (Head Image)",
                "verbose_name_plural": "3. Sahifalarda shiqadigan rasm (Head Image)",
            },
        ),
        migrations.CreateModel(
            name="HomeSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "Mavjud"), ("False", "Mavjud emas")],
                        default="False",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("title_uz", models.CharField(max_length=255, null=True)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_ru", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_uz", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_ru", models.TextField(blank=True, null=True)),
                (
                    "cover",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True, null=True, upload_to="images/"
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=555, null=True)),
            ],
            options={
                "verbose_name": "2. Bosh sahifa ushin rasim",
                "verbose_name_plural": "2. Bosh sahifa ushin rasim",
            },
        ),
        migrations.CreateModel(
            name="PaymentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "Mavjud"), ("False", "Mavjud emas")],
                        default="False",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("detail", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "detail_uz",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "detail_en",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "detail_ru",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
            ],
            options={
                "verbose_name": "8. Tolov tizimi haqqida",
                "verbose_name_plural": "8. Tolov tizimi haqqida",
            },
        ),
        migrations.CreateModel(
            name="ShippingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "Mavjud"), ("False", "Mavjud emas")],
                        default="False",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("detail", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "detail_uz",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "detail_en",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "detail_ru",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
            ],
            options={
                "verbose_name": "7. Yetkazip berish haqqida",
                "verbose_name_plural": "7. Yetkazip berish haqqida",
            },
        ),
    ]
