# Generated by Django 4.1.2 on 2022-10-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('shape', models.ImageField(blank=True, upload_to='images/')),
                ('cover', models.ImageField(blank=True, upload_to='images/')),
                ('status', models.CharField(choices=[('True', 'Published'), ('False', 'Not Published')], default='True', max_length=15)),
                ('url', models.CharField(blank=True, max_length=555)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
