# Generated by Django 4.1.2 on 2022-10-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shape', models.ImageField(upload_to='images/')),
                ('status', models.CharField(choices=[('True', 'Available'), ('False', 'Not Available')], default='True', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
