# Generated by Django 4.1.2 on 2022-10-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoninfo',
            name='description_contact_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='description_contact_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='description_contact_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='description_footer_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='description_footer_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='description_footer_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
