# Generated by Django 4.1.2 on 2022-11-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_commoninfo_description_contact_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('phone', models.CharField(max_length=222)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(max_length=500)),
                ('ip', models.CharField(blank=True, max_length=155)),
                ('status', models.CharField(choices=[('True', 'Oqilgan'), ('False', 'Oqilmagan')], default='False', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
