# Generated by Django 4.2.2 on 2023-07-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=40)),
                ("street_address_1", models.CharField(max_length=40)),
                ("street_address_2", models.CharField(max_length=40)),
                ("order_code", models.CharField(editable=False, max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "Yangi"),
                            ("Accepted", "Qabul qilindi"),
                            ("Preparing", "Tayyorlanmoqda"),
                            ("OnShipping", "Buyurtma yo'lda"),
                            ("Completed", "Buyurtma yetkazib berildi"),
                            ("Canceled", "Buyurtma bekor qilindi"),
                        ],
                        default="New",
                        max_length=30,
                    ),
                ),
                (
                    "payment_methot",
                    models.CharField(
                        choices=[
                            ("NAQD", "NAQD"),
                            ("CLICK", "CLICK"),
                            ("PAYME", "PAYME"),
                            ("CANCELED", "Bekor qilingan"),
                        ],
                        default="NAQD",
                        max_length=10,
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("offline_sales", models.BooleanField(default=False)),
                ("collection_order", models.BooleanField(default=False)),
                ("ip", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "verbose_name": "1. Buyirtma",
                "verbose_name_plural": "1. Buyirtmalar",
            },
        ),
        migrations.CreateModel(
            name="Shipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField()),
                ("wight", models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                "verbose_name": "2. Yetkazip beruvshi",
                "verbose_name_plural": "2. Yetkazip beruvshilar",
            },
        ),
        migrations.CreateModel(
            name="OrderLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField(blank=True, default=0, null=True)),
                ("collection_order_status", models.BooleanField(default=False)),
                (
                    "collection_book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item",
                        to="book.collectionbook",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item",
                        to="order.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item",
                        to="book.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "3. Buyirtma savatchasi",
                "verbose_name_plural": "3. Buyirtma savatchasi",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="shipping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="order.shipping",
            ),
        ),
    ]
