# Generated by Django 4.1.2 on 2022-11-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offline_sales',
            field=models.BooleanField(default=False),
        ),
    ]
