# Generated by Django 4.2.2 on 2023-07-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("administration", "0001_initial"),
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopcart",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shopcart_product",
                to="book.book",
            ),
        ),
    ]
