# Generated by Django 4.2.2 on 2023-07-04 15:59

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=355, unique=True)),
                ("title_uz", models.CharField(max_length=355, null=True, unique=True)),
                ("title_en", models.CharField(max_length=355, null=True, unique=True)),
                ("title_ru", models.CharField(max_length=355, null=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_uz", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_ru", models.TextField(blank=True, null=True)),
                ("text", ckeditor_uploader.fields.RichTextUploadingField()),
                ("text_uz", ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ("text_en", ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ("text_ru", ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(upload_to="blog/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "Chop etilgan"), ("False", "Chop etilmagan")],
                        default="True",
                        max_length=15,
                    ),
                ),
                ("views", models.PositiveBigIntegerField(default=0)),
                ("slug", models.SlugField(max_length=400, unique=True)),
            ],
            options={
                "verbose_name": "1. Yangilik",
                "verbose_name_plural": "1. Yangiliklar",
            },
        ),
        migrations.CreateModel(
            name="CategoryBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50)),
                ("title_uz", models.CharField(max_length=50, null=True)),
                ("title_en", models.CharField(max_length=50, null=True)),
                ("title_ru", models.CharField(max_length=50, null=True)),
                ("slug", models.SlugField(max_length=400, unique=True)),
            ],
            options={
                "verbose_name": "2. Yangilik kategoryasi",
                "verbose_name_plural": "2. Yangiliklar kategoryasi",
            },
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=55)),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("comment", models.TextField(max_length=355)),
                ("ip", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "Blok qoyilmagan"), ("False", "Bloklangan")],
                        default="True",
                        max_length=15,
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogcomment",
                        to="blog.blog",
                    ),
                ),
            ],
            options={
                "verbose_name": "3. Yangilik izohi",
                "verbose_name_plural": "3. Yangiliklar izohi",
            },
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog",
                to="blog.categoryblog",
            ),
        ),
    ]
